AutoSaving
Clipteam/clipcc-desktop pull request #4
Opened 2021-11-10 02:16 UTC by littlefrogfromthenorth

自动保存：
- 保存可以直接保存至原路径，无需每次都重选路径

界面的汉化
- 完全汉化界面，所有弹框，消息无英文

2021-11-10 02:18 UTC, littlefrogfromthenorth commented
效果预览：

https://github.com/littlefrogfromthenorth/clipcc-desktop/runs/4160241549?check_suite_focus=true

2021-11-10 05:33 UTC, frank-782 commented on src/main/index.js
> +			if (choice === 1) {
choice未定义

2021-11-10 13:29 UTC, SinanGentoo requested changes
请修改。

2021-11-10 13:29 UTC, SinanGentoo commented on src/main/index.js
> +        message = 'Clipcc �޷������������ͷ������ܻᵼ�²��ֹ����޷�����';
Clipcc改为ClipCC

PS：引入l10n支持会不会更好呢

2021-11-10 13:29 UTC, SinanGentoo commented on src/main/index.js
> +        message = 'Clipcc �޷����������˷磬����ܻᵼ�²��ֹ����޷�����';
同上

2021-11-10 13:29 UTC, SinanGentoo commented on src/main/index.js
> +        message = 'Clipcc �޷�ʹ��ĳЩȨ�ޣ�����ܻᵼ�²��ֹ����޷�����';
同上

2021-11-10 13:29 UTC, SinanGentoo commented on src/main/index.js
> +				detail: `��⵽��ǰ�ļ��Ѿ���������Ƿ�Ҫ���浽ԭ·����\n${downloadPath}.`,
应当在已经保存过一次后直接进行保存，如有需要请另加另存为菜单

2021-11-10 13:50 UTC, frank-782 commented on src/main/index.js
> +        message = 'Clipcc �޷������������ͷ������ܻᵼ�²��ֹ����޷�����';
字符请使用UTF-8进行编码 你这用的是GBK编码在我的环境下会乱码

2021-11-11 00:38 UTC, littlefrogfromthenorth commented
changed

2021-11-11 00:39 UTC, littlefrogfromthenorth commented
i10n 就不用了，这几个弹框还单独弄个多语言支持....不必要

2021-11-11 02:45 UTC, littlefrogfromthenorth commented
不好了，版本乱套了，待会另开pr吧

2021-11-11 02:45 UTC, closed without merging